### ISSUE TITLE
How to handle a function that is also kind of a namespace

### ISSUE THREAD

**Issue by theodoreb** [hegemonic/jsdoc-baseline#116]
As far as I know from looking into it last year, all the data is available from the parser. In short this is what I have: 

```
Drupal.displace = function () {};

Drupal.displace.offsets = {};
Drupal.displace.calculateOffsets = function () {};
```

Everything is JSDoc'ed and I'd like people to see the doc for everything. Right now I can only have `Drupal.displace` documented OR declare it as a namespace, loose the doc and have the two other properties documented. To have a example of a doc output: http://read.theodoreb.net/drupal-jsapi/Drupal.html#displace and the corresponding JS source: http://read.theodoreb.net/drupal-jsapi/displace.js.html#line40

Ideally I'd have the function doc just like it's displayed above but also the accompanying page that would show up if I'd use a `@namespace` tag on `Drupal.displace`.

- do you think it's doable and would you accept to have it in this template?
- if yes, any pointer as to where I can start looking? I'm happy to work on this, I'm just not familiar with this template code (yet) and been out of the jsdoc loop for pretty much a year. 

You can see I've started my own template https://github.com/theodoreb/drupal-js-api but I'd rather rely on this one to reduce maintenance on our side while helping out others when we find improvements to make on the template.

**Comment by hegemonic** [comment]
@theodoreb Using Baseline is an excellent medium- to long-term decision. You may experience a little pain in the short term, because:

+ The template is still evolving rapidly.
+ I'm still building the mechanism by which you can easily extend/modify the template without forking it. (I hope to finish this work in the next few weeks, though. Keep an eye on #117.)

In the immediate term, you might want to look at the current version of JSDoc's default template, which produces much nicer-looking output than it did even a few months ago.

Regarding your question: Yes, Baseline should and will support this pattern. Here's a smaller test case that I made to help myself out; right now, `Foo.staticMethod.nestedStaticMethod` does not appear in the docs:

```js
/**
 * @namespace
 */
var Foo = {};

/** Static method. */
Foo.staticMethod = function() {};

/** Nested static method. */
Foo.staticMethod.nestedStaticMethod = function() {};
```

I'm not sure exactly which files will need to change in order to support this pattern. At a high level, we'll need to look for members of functions (other than class constructors), then pass the list of members to the [properties partial](https://github.com/hegemonic/jsdoc-baseline/blob/master/views/atoms/properties.hbs).

If you don't mind waiting for a bit, I'll be happy to look into this myself. If you'd like to take a shot, though, here's an [overview of the Baseline template](https://docs.google.com/document/d/1H26OrUaP0RFU_envNq1m3QYazxmWL8gkgxYZQuwx5Ic/edit?usp=sharing), including instructions for setting up a development environment. (This info will eventually make its way into the Baseline docs.)

**Comment by theodoreb** [comment]
Thanks for the infos, don't worry about the pain, I have to rewrite all our docs to proper JSDoc so I'm pretty sure anything related to template won't be that bad.

I'll look this up and take the updated default template for a spin :)

**Comment by hegemonic** [comment]
Sounds like a plan.

Also, since you've been away from JSDoc for a while, you might want to take a look at the [draft changelog for JSDoc 3.3.0](https://github.com/jsdoc3/jsdoc/blob/master/CHANGES.md) to see what else is new.

**Comment by hegemonic** [comment]
Baseline now supports this pattern thanks to 6cb27d4b54e0af3837741fd43857fda3ceea78da and 46a60ec4f33e650beab11642cf2218af8d7f8880.

**Comment by theodoreb** [comment]
<img src="http://s2.quickmeme.com/img/7b/7bab45c9ab597e3821e31af7f1ae73601963a0cc1ea904487cb9e387a15e04db.jpg" alt="excellent">
